name: Recon + Vuln Scanner Automation 
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  DOMAIN: 'sharda.ac.in'

jobs:
  recon:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.19 
    
    - name: Install Required Tools 
      run: |
        go install -v github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest
        go install -v github.com/projectdiscovery/httpx/cmd/httpx@latest
        go install github.com/tomnomnom/waybackurls@latest
        go install -v github.com/projectdiscovery/nuclei/v2/cmd/nuclei@latest
        sudo apt-get update
        sudo apt-get -y install python3 python3-pip
        sudo pip3 install requests argparse dnspython
        git clone https://github.com/m4ll0k/SecretFinder ~/SecretFinder
        echo "installing additional dependency of SecretFinder"
        pip3 install -r ~/SecretFinder/requirements.txt
      shell: bash
    
    - name: Recon + Vuln Scanning 
      run: |
        echo "Target: $DOMAIN"
        subfinder -d $DOMAIN -o subfinder_output.txt 
        cat subfinder_output.txt | httpx -o httpx_result.txt 
        cat httpx_result.txt | waybackurls | tee -a endpoints.txt
        cat endpoints.txt | nuclei -es info | tee -a vulnscanner.txt
      shell: bash 
    
    - name: Js analyzing 
      run: |
        echo "Active Js analyzing to find Sensative Data Disclosure"
        cat endpoints.txt | while read js ; do python3 ~/SecretFinder/SecretFinder.py -i $js -o cli | tee -a js_disclosure.txt;done
      shell: bash

    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: Recon results
        path: subfinder_output.txt | httpx_result.txt | endpoints.txt | vulnscanner.txt | js_disclosure.txt
